import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'

export default function Home({ exploreData, cardsData }) {
  return (
    <>
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className='max-w-7xl mx-auto px-6 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Exlore Nearby</h2>
          <div className='grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {
              exploreData?.map((data) =>
                <SmallCard
                  key={data.location}
                  image={data.img}
                  location={data.location}
                  distance={data.distance} />
              )
            }
          </div>
        </section>

        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Live Anywhere</h2>
          <div className='flex space-x-4 overflow-x-scroll overflow-y-hidden scrollbar-hide p-3'>
            {
              cardsData?.map((data) =>
                <MediumCard
                  key={''}
                  title={data.title}
                  img={data.img} />
              )
            }
          </div>
        </section>

        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoor"
          description="Wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>
    </>
  )
}


export async function getStaticProps() {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').then((res) => res.json())
  const cardsData = await fetch('https://www.jsonkeeper.com/b/Q7XM').then((res) => res.json())
  return {
    props: {
      exploreData,
      cardsData: cardsData?.places
    }
  }
}